services:

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'planner-rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672

    restart: 'always'
    environment:
      RABBITMQ_PASSWORD: admin
      RABBITMQ_USERNAME: admin