spring:
  config:
    activate:
      on-profile: ide

  mail:
    host: smtp.gmail.com
    port: 587
    username: task.tracker.email.sender@gmail.com
    password: csxhhpurugycqfaq
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  rabbitmq:
    host: localhost
    port: 5672







