spring:
  config:
    activate:
      on-profile: prod

  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

rabbitmq:
  key:
    greetings:
    analytics:
  queue:
    greetings:
    analytics:
  exchange:

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://task-tracker-service-discovery:8761/eureka
