spring:
  application:
    name: task-tracker-email-sender

  rabbitmq:
    host: rabbitmq

  mail:
    host: smtp.gmail.com
    port: 587
    username: task.tracker.email.sender@gmail.com
    password: csxhhpurugycqfaq
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8081

rabbitmq:
  key: key
  queue: EMAIL_SENDING_TASKS
  exchange: exchange

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://task-tracker-service-discovery:8761/eureka
