spring:
  application:
    name: task-tracker-email-sender

  profiles:
    active: ide



rabbitmq:
  key:
    greetings: KEY1
    analytics: KEY2
  queue:
    greetings: EMAIL_GREEATINGS_TASKS
    analytics: EMAIL_ANALITICS_TASKS
  exchange: exchange


logging:
  file:
    path: ./src/main/resources/logs
    name: ${logging.file.path}/task-tracker-email-sender.log
  logback:
    rollingpolicy:
      max-file-size: 1000000
      clean-history-on-start: true